name: "Packagist Update"

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Packagist Update
        uses: mnavarrocarter/packagist-update@v1.0.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
