name: "Update Packagist"

on:
  release:
    types: [ released ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Update Packagist
        uses: mnavarrocarter/packagist-update@v1.0
        with:
          username: ${{ secrets.PACKAGIST_USERNAME }}
          api_token: ${{ secrets.PACKAGIST_TOKEN }}
